site_name: AutoThemeGenerator
nav:
  - Home: index.md
  - Documentation: documention.md
  - Examples: examples.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true